FROM golang:latest
# Update the system
RUN apt update && apt upgrade -y
# Install dependencies 
RUN apt install -y git build-essential curl jq
# Confirm Go version
RUN go version
# Install osmosisd
WORKDIR /app
RUN git clone https://github.com/cosmos/cosmos-sdk
WORKDIR /app/cosmos-sdk
ARG COSMOVISOR_VERSION
RUN git checkout $COSMOVISOR_VERSION
RUN make cosmovisor

RUN cp cosmovisor/cosmovisor $GOPATH/bin/cosmovisor
